//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataFramework.Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportOutputColumnCustomization
    {
        public int pkID { get; set; }
        public int fkUser { get; set; }
        public int Position { get; set; }
        public int Flags { get; set; }
        public string DisplayName { get; set; }
        public int fkColumn { get; set; }
        public string DisplayType { get; set; }
    
        public virtual ReportOutputColumn ReportOutputColumn { get; set; }
    }
}
